[workspace]
members = [
    ".",
    "game_engine",
    "test_rapier_sync",
    "test_physics_world_sync"
]
resolver = "3"

[workspace.dependencies]
# Core dependencies
wgpu = "27.0.1"
winit = "0.31"
bevy_ecs = "0.17.3"
glam = { version = "0.30.9", features = ["bytemuck", "serde"] }
tokio = { version = "1.48", features = ["full"] }

# Common dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
parking_lot = "0.12.5"
crossbeam = "0.8"
tracing = "0.1"