//! # 脚本生成器
//!
//! 从编辑操作自动生成脚本，支持：
//! - Lua
//! - Python
//! - Rust代码
//!
//! 将DCC工具中的编辑操作转换为可执行脚本。

use crate::render::pbr::{PbrMaterial, PbrMaterialFull};
use crate::tools::dcc::{
    animation_editor::{AnimationID, KeyframeID},
    material_editor::MaterialID,
    mesh_editor::MeshOperation,
};
use glam::{Mat4, Vec3, Vec4};
use std::fmt;

/// 脚本语言
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScriptLanguage {
    /// Lua脚本
    Lua,
    /// Python脚本
    Python,
    /// Rust代码
    Rust,
}

impl fmt::Display for ScriptLanguage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ScriptLanguage::Lua => write!(f, "Lua"),
            ScriptLanguage::Python => write!(f, "Python"),
            ScriptLanguage::Rust => write!(f, "Rust"),
        }
    }
}

/// 编辑器操作
#[derive(Debug, Clone)]
pub enum EditorOperation {
    /// 顶点变换
    VertexTransform { vertices: Vec<u32>, transform: Mat4 },
    /// 材质更改
    MaterialChange {
        material: MaterialID,
        params: PbrMaterialParams,
    },
    /// 添加关键帧
    KeyframeAdd {
        animation: AnimationID,
        frame: f32,
        value: AnimatedValue,
    },
    /// UV变换
    UVTransform {
        uvs: Vec<usize>,
        translation: (f32, f32),
        rotation: f32,
        scale: (f32, f32),
    },
}

/// PBR材质参数（简化版）
#[derive(Debug, Clone)]
pub struct PbrMaterialParams {
    pub base_color: Vec4,
    pub metallic: f32,
    pub roughness: f32,
    pub ambient_occlusion: f32,
    pub emissive: Vec3,
    pub normal_scale: f32,
}

impl From<PbrMaterial> for PbrMaterialParams {
    fn from(mat: PbrMaterial) -> Self {
        Self {
            base_color: mat.base_color,
            metallic: mat.metallic,
            roughness: mat.roughness,
            ambient_occlusion: mat.ambient_occlusion,
            emissive: mat.emissive,
            normal_scale: mat.normal_scale,
        }
    }
}

/// 动画值
#[derive(Debug, Clone)]
pub enum AnimatedValue {
    Float(f32),
    Vec3(Vec3),
    Quat(glam::Quat),
}

/// 导出选项
#[derive(Debug, Clone)]
pub struct ExportOptions {
    /// 添加注释
    pub add_comments: bool,
    /// 格式化代码
    pub format_code: bool,
    /// 添加错误处理
    pub add_error_handling: bool,
    /// 包含头注释
    pub include_header: bool,
}

impl Default for ExportOptions {
    fn default() -> Self {
        Self {
            add_comments: true,
            format_code: true,
            add_error_handling: true,
            include_header: true,
        }
    }
}

/// 生成的脚本
#[derive(Debug, Clone)]
pub struct GeneratedScript {
    /// 脚本代码
    pub code: String,
    /// 语言
    pub language: ScriptLanguage,
    /// 操作数量
    pub operation_count: usize,
}

/// 脚本生成器
#[derive(Debug, Clone)]
pub struct ScriptGenerator {
    /// 操作列表
    operations: Vec<EditorOperation>,
    /// 导出选项
    export_options: ExportOptions,
}

impl ScriptGenerator {
    /// 创建新的脚本生成器
    pub fn new() -> Self {
        Self {
            operations: Vec::new(),
            export_options: ExportOptions::default(),
        }
    }

    /// 添加操作
    pub fn add_operation(&mut self, operation: EditorOperation) {
        self.operations.push(operation);
    }

    /// 获取操作列表
    pub fn operations(&self) -> &[EditorOperation] {
        &self.operations
    }

    /// 清除操作
    pub fn clear_operations(&mut self) {
        self.operations.clear();
    }

    /// 生成脚本
    pub fn generate_script(&self, language: ScriptLanguage) -> GeneratedScript {
        let code = match language {
            ScriptLanguage::Lua => self.generate_lua_script(),
            ScriptLanguage::Python => self.generate_python_script(),
            ScriptLanguage::Rust => self.generate_rust_code(),
        };

        GeneratedScript {
            code,
            language,
            operation_count: self.operations.len(),
        }
    }

    /// 生成Lua脚本
    fn generate_lua_script(&self) -> String {
        let mut script = String::new();

        // 头注释
        if self.export_options.include_header {
            script.push_str("-- Auto-generated DCC script\n");
            script.push_str(&format!(
                "-- Generated by game_engine v{}\n",
                env!("CARGO_PKG_VERSION")
            ));
            script.push_str(&format!("-- Operations: {}\n\n", self.operations.len()));
        }

        if self.export_options.add_error_handling {
            script.push_str("local status, err = pcall(function()\n");
        }

        for op in &self.operations {
            match op {
                EditorOperation::VertexTransform {
                    vertices,
                    transform,
                } => {
                    if self.export_options.add_comments {
                        script.push_str("\n-- Transform vertices\n");
                    }

                    let vertices_str =
                        vertices.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", ");

                    script.push_str(&format!("local vertices = {{{}}}\n", vertices_str));
                    script.push_str("for _, vid in ipairs(vertices) do\n");
                    script.push_str(&format!(
                        "    mesh:set_vertex_position(vid, transform({}))\n",
                        self.mat4_to_lua(transform)
                    ));
                    script.push_str("end\n");
                }
                EditorOperation::MaterialChange { material, params } => {
                    if self.export_options.add_comments {
                        script.push_str(&format!("\n-- Change material {}\n", material));
                    }

                    script.push_str(&format!("local mat = mesh:get_material({})\n", material));
                    script.push_str(&format!(
                        "mat.base_color = {{{}}}\n",
                        self.vec4_to_lua(&params.base_color)
                    ));
                    script.push_str(&format!("mat.metallic = {}\n", params.metallic));
                    script.push_str(&format!("mat.roughness = {}\n", params.roughness));
                    script.push_str(&format!("mat.ao = {}\n", params.ambient_occlusion));
                    script.push_str(&format!(
                        "mat.emissive = {{{}}}\n",
                        self.vec3_to_lua(&params.emissive)
                    ));
                    script.push_str("mesh:set_material(mat)\n");
                }
                EditorOperation::KeyframeAdd {
                    animation,
                    frame,
                    value,
                } => {
                    if self.export_options.add_comments {
                        script.push_str(&format!("\n-- Add keyframe to animation {}\n", animation));
                    }

                    script.push_str(&format!("local anim = get_animation({})\n", animation));
                    script.push_str(&format!(
                        "anim:add_keyframe({}, {})\n",
                        frame,
                        self.animated_value_to_lua(value)
                    ));
                }
                EditorOperation::UVTransform {
                    uvs,
                    translation,
                    rotation,
                    scale,
                } => {
                    if self.export_options.add_comments {
                        script.push_str("\n-- Transform UVs\n");
                    }

                    let uvs_str = uvs.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", ");
                    script.push_str(&format!("local uv_indices = {{{}}}\n", uvs_str));
                    script.push_str("for _, uv_id in ipairs(uv_indices) do\n");
                    script.push_str(&format!(
                        "    mesh:set_uv_translation(uv_id, {}, {})\n",
                        translation.0, translation.1
                    ));
                    script.push_str(&format!("    mesh:set_uv_rotation(uv_id, {})\n", rotation));
                    script.push_str(&format!(
                        "    mesh:set_uv_scale(uv_id, {}, {})\n",
                        scale.0, scale.1
                    ));
                    script.push_str("end\n");
                }
            }
        }

        if self.export_options.add_error_handling {
            script.push_str("end)\n\n");
            script.push_str("if not status then\n");
            script.push_str("    print(\"Error: \" .. tostring(err))\n");
            script.push_str("end\n");
        }

        script
    }

    /// 生成Python脚本
    fn generate_python_script(&self) -> String {
        let mut script = String::new();

        // 头注释
        if self.export_options.include_header {
            script.push_str("# Auto-generated DCC script\n");
            script.push_str(&format!(
                "# Generated by game_engine v{}\n",
                env!("CARGO_PKG_VERSION")
            ));
            script.push_str(&format!("# Operations: {}\n\n", self.operations.len()));
        }

        script.push_str("import game_engine as ge\n\n");

        if self.export_options.add_error_handling {
            script.push_str("try:\n");
        }

        for op in &self.operations {
            match op {
                EditorOperation::VertexTransform {
                    vertices,
                    transform,
                } => {
                    if self.export_options.add_comments {
                        script.push_str("\n    # Transform vertices\n");
                    }

                    script.push_str(&format!(
                        "    vertices = [{}]\n",
                        vertices.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", ")
                    ));
                    script.push_str("    for vid in vertices:\n");
                    script.push_str(&format!(
                        "        mesh.set_vertex_position(vid, {})\n",
                        self.mat4_to_python(transform)
                    ));
                }
                EditorOperation::MaterialChange { material, params } => {
                    if self.export_options.add_comments {
                        script.push_str(&format!("\n    # Change material {}\n", material));
                    }

                    script.push_str(&format!("    mat = mesh.get_material({})\n", material));
                    script.push_str(&format!(
                        "    mat.base_color = {}\n",
                        self.vec4_to_python(&params.base_color)
                    ));
                    script.push_str(&format!("    mat.metallic = {}\n", params.metallic));
                    script.push_str(&format!("    mat.roughness = {}\n", params.roughness));
                    script.push_str(&format!("    mat.ao = {}\n", params.ambient_occlusion));
                    script.push_str(&format!(
                        "    mat.emissive = {}\n",
                        self.vec3_to_python(&params.emissive)
                    ));
                    script.push_str("    mesh.set_material(mat)\n");
                }
                EditorOperation::KeyframeAdd {
                    animation,
                    frame,
                    value,
                } => {
                    if self.export_options.add_comments {
                        script.push_str(&format!(
                            "\n    # Add keyframe to animation {}\n",
                            animation
                        ));
                    }

                    script.push_str(&format!("    anim = get_animation({})\n", animation));
                    script.push_str(&format!(
                        "    anim.add_keyframe({}, {})\n",
                        frame,
                        self.animated_value_to_python(value)
                    ));
                }
                EditorOperation::UVTransform {
                    uvs,
                    translation,
                    rotation,
                    scale,
                } => {
                    if self.export_options.add_comments {
                        script.push_str("\n    # Transform UVs\n");
                    }

                    script.push_str(&format!(
                        "    uv_indices = [{}]\n",
                        uvs.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", ")
                    ));
                    script.push_str("    for uv_id in uv_indices:\n");
                    script.push_str(&format!(
                        "        mesh.set_uv_translation(uv_id, {}, {})\n",
                        translation.0, translation.1
                    ));
                    script.push_str(&format!(
                        "        mesh.set_uv_rotation(uv_id, {})\n",
                        rotation
                    ));
                    script.push_str(&format!(
                        "        mesh.set_uv_scale(uv_id, {}, {})\n",
                        scale.0, scale.1
                    ));
                }
            }
        }

        if self.export_options.add_error_handling {
            script.push_str("\nexcept Exception as e:\n");
            script.push_str("    print(f\"Error: {e}\")\n");
        }

        script
    }

    /// 生成Rust代码
    fn generate_rust_code(&self) -> String {
        let mut code = String::new();

        // 头注释
        if self.export_options.include_header {
            code.push_str("// Auto-generated DCC code\n");
            code.push_str(&format!(
                "// Generated by game_engine v{}\n",
                env!("CARGO_PKG_VERSION")
            ));
            code.push_str(&format!("// Operations: {}\n\n", self.operations.len()));
        }

        code.push_str("use game_engine::prelude::*;\n");
        code.push_str("use glam::*;\n\n");

        code.push_str("pub fn apply_operations(mesh: &mut Mesh) -> Result<(), Box<dyn std::error::Error>> {\n");

        for op in &self.operations {
            match op {
                EditorOperation::VertexTransform {
                    vertices,
                    transform,
                } => {
                    if self.export_options.add_comments {
                        code.push_str("\n    // Transform vertices\n");
                    }

                    code.push_str("    let vertices: Vec<u32> = vec![");
                    code.push_str(
                        &vertices.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", "),
                    );
                    code.push_str("];\n");

                    code.push_str("    for &vid in &vertices {\n");
                    code.push_str(&format!(
                        "        let pos = mesh.get_vertex_position(vid)?;\n"
                    ));
                    code.push_str(&format!(
                        "        let new_pos = {} * pos.extend(1.0);\n",
                        self.mat4_to_rust(transform)
                    ));
                    code.push_str(&format!(
                        "        mesh.set_vertex_position(vid, new_pos.truncate())?;\n"
                    ));
                    code.push_str("    }\n");
                }
                EditorOperation::MaterialChange { material, params } => {
                    if self.export_options.add_comments {
                        code.push_str(&format!("\n    // Change material {}\n", material));
                    }

                    code.push_str(&format!(
                        "    let mut mat = mesh.get_material({})?;\n",
                        material
                    ));
                    code.push_str(&format!(
                        "    mat.base_color = {};\n",
                        self.vec4_to_rust(&params.base_color)
                    ));
                    code.push_str(&format!("    mat.metallic = {};\n", params.metallic));
                    code.push_str(&format!("    mat.roughness = {};\n", params.roughness));
                    code.push_str(&format!(
                        "    mat.ambient_occlusion = {};\n",
                        params.ambient_occlusion
                    ));
                    code.push_str(&format!(
                        "    mat.emissive = {};\n",
                        self.vec3_to_rust(&params.emissive)
                    ));
                    code.push_str(&format!("    mesh.set_material({}, mat)?;\n", material));
                }
                EditorOperation::KeyframeAdd {
                    animation,
                    frame,
                    value,
                } => {
                    if self.export_options.add_comments {
                        code.push_str(&format!(
                            "\n    // Add keyframe to animation {}\n",
                            animation
                        ));
                    }

                    code.push_str(&format!(
                        "    let anim = engine.get_animation({})?;\n",
                        animation
                    ));
                    code.push_str(&format!(
                        "    anim.add_keyframe({}, {})?;\n",
                        frame,
                        self.animated_value_to_rust(value)
                    ));
                }
                EditorOperation::UVTransform {
                    uvs,
                    translation,
                    rotation,
                    scale,
                } => {
                    if self.export_options.add_comments {
                        code.push_str("\n    // Transform UVs\n");
                    }

                    code.push_str("    let uv_indices: Vec<usize> = vec![");
                    code.push_str(
                        &uvs.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(", "),
                    );
                    code.push_str("];\n");

                    code.push_str("    for &uv_id in &uv_indices {\n");
                    code.push_str(&format!(
                        "        mesh.set_uv_translation(uv_id, Vec2::new({}, {}))?;\n",
                        translation.0, translation.1
                    ));
                    code.push_str(&format!(
                        "        mesh.set_uv_rotation(uv_id, {})?;\n",
                        rotation
                    ));
                    code.push_str(&format!(
                        "        mesh.set_uv_scale(uv_id, Vec2::new({}, {}))?;\n",
                        scale.0, scale.1
                    ));
                    code.push_str("    }\n");
                }
            }
        }

        code.push_str("\n    Ok(())\n");
        code.push_str("}\n");

        code
    }

    // 辅助方法：转换Mat4为Lua
    fn mat4_to_lua(&self, mat: &Mat4) -> String {
        format!(
            "Mat4.new({},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{})",
            mat.x_axis.x,
            mat.x_axis.y,
            mat.x_axis.z,
            mat.x_axis.w,
            mat.y_axis.x,
            mat.y_axis.y,
            mat.y_axis.z,
            mat.y_axis.w,
            mat.z_axis.x,
            mat.z_axis.y,
            mat.z_axis.z,
            mat.z_axis.w,
            mat.w_axis.x,
            mat.w_axis.y,
            mat.w_axis.z,
            mat.w_axis.w,
        )
    }

    // 辅助方法：转换Mat4为Python
    fn mat4_to_python(&self, mat: &Mat4) -> String {
        format!(
            "ge.Mat4({},{},{},{},{},{},{},{},{},{},{},{},{},{},{},{})",
            mat.x_axis.x,
            mat.x_axis.y,
            mat.x_axis.z,
            mat.x_axis.w,
            mat.y_axis.x,
            mat.y_axis.y,
            mat.y_axis.z,
            mat.y_axis.w,
            mat.z_axis.x,
            mat.z_axis.y,
            mat.z_axis.z,
            mat.z_axis.w,
            mat.w_axis.x,
            mat.w_axis.y,
            mat.w_axis.z,
            mat.w_axis.w,
        )
    }

    // 辅助方法：转换Mat4为Rust
    fn mat4_to_rust(&self, mat: &Mat4) -> String {
        format!(
            "Mat4::from_cols({}, {}, {}, {})",
            self.vec4_to_rust(&mat.x_axis.into()),
            self.vec4_to_rust(&mat.y_axis.into()),
            self.vec4_to_rust(&mat.z_axis.into()),
            self.vec4_to_rust(&mat.w_axis.into()),
        )
    }

    // 辅助方法：转换Vec4为Lua
    fn vec4_to_lua(&self, v: &Vec4) -> String {
        format!("{},{},{},{}", v.x, v.y, v.z, v.w)
    }

    // 辅助方法：转换Vec4为Python
    fn vec4_to_python(&self, v: &Vec4) -> String {
        format!("ge.Vec4({}, {}, {}, {})", v.x, v.y, v.z, v.w)
    }

    // 辅助方法：转换Vec4为Rust
    fn vec4_to_rust(&self, v: &Vec4) -> String {
        format!("Vec4::new({}, {}, {}, {})", v.x, v.y, v.z, v.w)
    }

    // 辅助方法：转换Vec3为Lua
    fn vec3_to_lua(&self, v: &Vec3) -> String {
        format!("{},{},{}", v.x, v.y, v.z)
    }

    // 辅助方法：转换Vec3为Python
    fn vec3_to_python(&self, v: &Vec3) -> String {
        format!("ge.Vec3({}, {}, {})", v.x, v.y, v.z)
    }

    // 辅助方法：转换Vec3为Rust
    fn vec3_to_rust(&self, v: &Vec3) -> String {
        format!("Vec3::new({}, {}, {})", v.x, v.y, v.z)
    }

    // 辅助方法：转换动画值为Lua
    fn animated_value_to_lua(&self, value: &AnimatedValue) -> String {
        match value {
            AnimatedValue::Float(v) => v.to_string(),
            AnimatedValue::Vec3(v) => format!("Vec3.new({},{},{})", v.x, v.y, v.z),
            AnimatedValue::Quat(q) => format!("Quat.new({},{},{},{})", q.x, q.y, q.z, q.w),
        }
    }

    // 辅助方法：转换动画值为Python
    fn animated_value_to_python(&self, value: &AnimatedValue) -> String {
        match value {
            AnimatedValue::Float(v) => v.to_string(),
            AnimatedValue::Vec3(v) => format!("ge.Vec3({}, {}, {})", v.x, v.y, v.z),
            AnimatedValue::Quat(q) => format!("ge.Quat({}, {}, {}, {})", q.x, q.y, q.z, q.w),
        }
    }

    // 辅助方法：转换动画值为Rust
    fn animated_value_to_rust(&self, value: &AnimatedValue) -> String {
        match value {
            AnimatedValue::Float(v) => v.to_string(),
            AnimatedValue::Vec3(v) => format!("Vec3::new({}, {}, {})", v.x, v.y, v.z),
            AnimatedValue::Quat(q) => {
                format!("Quat::from_xyzw({}, {}, {}, {})", q.x, q.y, q.z, q.w)
            }
        }
    }
}

impl Default for ScriptGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_script_generator_creation() {
        let generator = ScriptGenerator::new();
        assert!(generator.operations().is_empty());
    }

    #[test]
    fn test_add_operation() {
        let mut generator = ScriptGenerator::new();
        let op = EditorOperation::VertexTransform {
            vertices: vec![0, 1, 2],
            transform: Mat4::IDENTITY,
        };

        generator.add_operation(op);
        assert_eq!(generator.operations().len(), 1);
    }

    #[test]
    fn test_generate_lua_script() {
        let mut generator = ScriptGenerator::new();

        let op = EditorOperation::VertexTransform {
            vertices: vec![0, 1, 2],
            transform: Mat4::IDENTITY,
        };

        generator.add_operation(op);

        let script = generator.generate_script(ScriptLanguage::Lua);
        assert!(script.code.contains("-- Auto-generated"));
        assert!(script.code.contains("Transform vertices"));
        assert_eq!(script.operation_count, 1);
    }

    #[test]
    fn test_generate_python_script() {
        let mut generator = ScriptGenerator::new();

        let op = EditorOperation::VertexTransform {
            vertices: vec![0, 1, 2],
            transform: Mat4::IDENTITY,
        };

        generator.add_operation(op);

        let script = generator.generate_script(ScriptLanguage::Python);
        assert!(script.code.contains("# Auto-generated"));
        assert!(script.code.contains("Transform vertices"));
        assert_eq!(script.operation_count, 1);
    }

    #[test]
    fn test_generate_rust_code() {
        let mut generator = ScriptGenerator::new();

        let op = EditorOperation::VertexTransform {
            vertices: vec![0, 1, 2],
            transform: Mat4::IDENTITY,
        };

        generator.add_operation(op);

        let script = generator.generate_script(ScriptLanguage::Rust);
        assert!(script.code.contains("// Auto-generated"));
        assert!(script.code.contains("Transform vertices"));
        assert_eq!(script.operation_count, 1);
    }

    #[test]
    fn test_clear_operations() {
        let mut generator = ScriptGenerator::new();

        let op = EditorOperation::VertexTransform {
            vertices: vec![0, 1, 2],
            transform: Mat4::IDENTITY,
        };

        generator.add_operation(op);
        generator.clear_operations();
        assert!(generator.operations().is_empty());
    }
}
