/**
 * 全局快捷键
 * 在所有上下文中都可用
 */

import { Shortcut } from '../types/shortcuts';

export const globalShortcuts: Shortcut[] = [
  // 文件操作
  {
    id: 'file.new',
    keys: [{ key: 'n', ctrl: true }],
    action: 'file.new',
    description: '新建场景',
    category: 'file',
    context: 'global',
    priority: 100,
  },
  {
    id: 'file.open',
    keys: [{ key: 'o', ctrl: true }],
    action: 'file.open',
    description: '打开场景',
    category: 'file',
    context: 'global',
    priority: 100,
  },
  {
    id: 'file.save',
    keys: [{ key: 's', ctrl: true }],
    action: 'file.save',
    description: '保存',
    category: 'file',
    context: 'global',
    priority: 100,
  },
  {
    id: 'file.saveAs',
    keys: [{ key: 's', ctrl: true, shift: true }],
    action: 'file.saveAs',
    description: '另存为',
    category: 'file',
    context: 'global',
    priority: 100,
  },
  {
    id: 'file.export',
    keys: [{ key: 'e', ctrl: true, shift: true }],
    action: 'file.export',
    description: '导出',
    category: 'file',
    context: 'global',
  },

  // 编辑操作
  {
    id: 'edit.undo',
    keys: [{ key: 'z', ctrl: true }],
    action: 'edit.undo',
    description: '撤销',
    category: 'edit',
    context: 'global',
    priority: 100,
  },
  {
    id: 'edit.redo',
    keys: [{ key: 'z', ctrl: true, shift: true }],
    action: 'edit.redo',
    description: '重做',
    category: 'edit',
    context: 'global',
    priority: 100,
  },
  {
    id: 'edit.cut',
    keys: [{ key: 'x', ctrl: true }],
    action: 'edit.cut',
    description: '剪切',
    category: 'edit',
    context: 'global',
  },
  {
    id: 'edit.copy',
    keys: [{ key: 'c', ctrl: true }],
    action: 'edit.copy',
    description: '复制',
    category: 'edit',
    context: 'global',
  },
  {
    id: 'edit.paste',
    keys: [{ key: 'v', ctrl: true }],
    action: 'edit.paste',
    description: '粘贴',
    category: 'edit',
    context: 'global',
  },
  {
    id: 'edit.duplicate',
    keys: [{ key: 'd', ctrl: true }],
    action: 'edit.duplicate',
    description: '复制选中',
    category: 'edit',
    context: 'global',
  },
  {
    id: 'edit.selectAll',
    keys: [{ key: 'a', ctrl: true }],
    action: 'edit.selectAll',
    description: '全选',
    category: 'edit',
    context: 'global',
  },
  {
    id: 'edit.delete',
    keys: [{ key: 'Delete' }],
    action: 'edit.delete',
    description: '删除选中',
    category: 'edit',
    context: 'global',
  },
  {
    id: 'edit.rename',
    keys: [{ key: 'F2' }],
    action: 'edit.rename',
    description: '重命名',
    category: 'edit',
    context: 'global',
  },

  // 面板切换
  {
    id: 'panel.entityTree',
    keys: [{ key: '1', ctrl: true }],
    action: 'panel.toggleEntityTree',
    description: '实体树',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.inspector',
    keys: [{ key: '2', ctrl: true }],
    action: 'panel.toggleInspector',
    description: '属性检查器',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.assets',
    keys: [{ key: '3', ctrl: true }],
    action: 'panel.toggleAssets',
    description: '资源浏览器',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.material',
    keys: [{ key: '4', ctrl: true }],
    action: 'panel.toggleMaterial',
    description: '材质编辑器',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.behavior',
    keys: [{ key: '5', ctrl: true }],
    action: 'panel.toggleBehavior',
    description: '行为树编辑器',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.timeline',
    keys: [{ key: '6', ctrl: true }],
    action: 'panel.toggleTimeline',
    description: '时间轴',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.console',
    keys: [{ key: '7', ctrl: true }],
    action: 'panel.toggleConsole',
    description: '控制台',
    category: 'view',
    context: 'global',
  },
  {
    id: 'panel.performance',
    keys: [{ key: 'F12' }],
    action: 'panel.togglePerformance',
    description: '性能仪表板',
    category: 'view',
    context: 'global',
  },

  // 工具
  {
    id: 'tools.settings',
    keys: [{ key: ',', ctrl: true }],
    action: 'tools.settings',
    description: '设置',
    category: 'tools',
    context: 'global',
  },
  {
    id: 'tools.shortcuts',
    keys: [{ key: 'k', ctrl: true }],
    action: 'tools.shortcuts',
    description: '快捷键设置',
    category: 'tools',
    context: 'global',
  },
  {
    id: 'tools.help',
    keys: [{ key: 'F1' }],
    action: 'tools.help',
    description: '帮助',
    category: 'help',
    context: 'global',
  },
  {
    id: 'docs.shortcuts',
    keys: [{ key: '/', ctrl: true }],
    action: 'docs.shortcuts',
    description: '快捷键参考',
    category: 'help',
    context: 'global',
  },

  // 窗口
  {
    id: 'window.close',
    keys: [{ key: 'w', ctrl: true }],
    action: 'window.close',
    description: '关闭当前面板',
    category: 'window',
    context: 'global',
  },
  {
    id: 'window.minimize',
    keys: [{ key: 'm', ctrl: true }],
    action: 'window.minimize',
    description: '最小化',
    category: 'window',
    context: 'global',
  },
  {
    id: 'window.maximize',
    keys: [{ key: 'f', ctrl: true, shift: true }],
    action: 'window.maximize',
    description: '最大化',
    category: 'window',
    context: 'global',
  },

  // 播放控制
  {
    id: 'playback.play',
    keys: [{ key: ' ' }],
    action: 'playback.play',
    description: '播放/暂停',
    category: 'playback',
    context: 'global',
  },
  {
    id: 'playback.stop',
    keys: [{ key: 'Escape' }],
    action: 'playback.stop',
    description: '停止',
    category: 'playback',
    context: 'global',
  },
];
