/**
 * 视口快捷键
 * 3D视口上下文中的快捷键
 */

import { Shortcut } from '../types/shortcuts';

export const viewportShortcuts: Shortcut[] = [
  // 变换工具
  {
    id: 'viewport.translate',
    keys: [{ key: 'w' }],
    action: 'viewport.setTranslateMode',
    description: '平移工具',
    category: 'transform',
    context: 'viewport',
    priority: 100,
  },
  {
    id: 'viewport.rotate',
    keys: [{ key: 'e' }],
    action: 'viewport.setRotateMode',
    description: '旋转工具',
    category: 'transform',
    context: 'viewport',
    priority: 100,
  },
  {
    id: 'viewport.scale',
    keys: [{ key: 'r' }],
    action: 'viewport.setScaleMode',
    description: '缩放工具',
    category: 'transform',
    context: 'viewport',
    priority: 100,
  },
  {
    id: 'viewport.select',
    keys: [{ key: 'q' }],
    action: 'viewport.setSelectMode',
    description: '选择工具',
    category: 'transform',
    context: 'viewport',
    priority: 100,
  },

  // 变换空间
  {
    id: 'viewport.togglePivot',
    keys: [{ key: 'p' }],
    action: 'viewport.togglePivot',
    description: '切换中心点',
    category: 'transform',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleCoordinateSpace',
    keys: [{ key: 'x' }],
    action: 'viewport.toggleCoordinateSpace',
    description: '切换坐标系',
    category: 'transform',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleSnap',
    keys: [{ key: 's', ctrl: true }],
    action: 'viewport.toggleSnap',
    description: '切换吸附',
    category: 'transform',
    context: 'viewport',
  },

  // 视图导航
  {
    id: 'viewport.frameSelected',
    keys: [{ key: 'f' }],
    action: 'viewport.frameSelected',
    description: '聚焦选中',
    category: 'navigation',
    context: 'viewport',
    priority: 90,
  },
  {
    id: 'viewport.frameAll',
    keys: [{ key: 'a', ctrl: true }],
    action: 'viewport.frameAll',
    description: '聚焦全部',
    category: 'navigation',
    context: 'viewport',
  },
  {
    id: 'viewport.topView',
    keys: [{ key: 't', ctrl: true, alt: true }],
    action: 'viewport.topView',
    description: '顶视图',
    category: 'navigation',
    context: 'viewport',
  },
  {
    id: 'viewport.frontView',
    keys: [{ key: 'f', ctrl: true, alt: true }],
    action: 'viewport.frontView',
    description: '前视图',
    category: 'navigation',
    context: 'viewport',
  },
  {
    id: 'viewport.rightView',
    keys: [{ key: 'r', ctrl: true, alt: true }],
    action: 'viewport.rightView',
    description: '右视图',
    category: 'navigation',
    context: 'viewport',
  },
  {
    id: 'viewport.perspectiveView',
    keys: [{ key: 'p', ctrl: true, alt: true }],
    action: 'viewport.perspectiveView',
    description: '透视图',
    category: 'navigation',
    context: 'viewport',
  },

  // 相机控制
  {
    id: 'viewport.cameraOrbit',
    keys: [{ key: 'Alt', ctrl: false, shift: false, alt: true }],
    action: 'viewport.cameraOrbit',
    description: '旋转相机（按住Alt+左键）',
    category: 'navigation',
    context: 'viewport',
  },
  {
    id: 'viewport.cameraPan',
    keys: [{ key: 'Shift', ctrl: false, shift: true, alt: true }],
    action: 'viewport.cameraPan',
    description: '平移相机（按住Shift+Alt+左键）',
    category: 'navigation',
    context: 'viewport',
  },
  {
    id: 'viewport.cameraZoom',
    keys: [{ key: ' ', ctrl: false, shift: false, alt: true }],
    action: 'viewport.cameraZoom',
    description: '缩放相机（按住Alt+右键）',
    category: 'navigation',
    context: 'viewport',
  },

  // 显示选项
  {
    id: 'viewport.toggleGrid',
    keys: [{ key: 'g' }],
    action: 'viewport.toggleGrid',
    description: '切换网格',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleStatistics',
    keys: [{ key: 'u' }],
    action: 'viewport.toggleStatistics',
    description: '切换统计信息',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleWireframe',
    keys: [{ key: 'z' }],
    action: 'viewport.toggleWireframe',
    description: '切换线框模式',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleBounds',
    keys: [{ key: 'b' }],
    action: 'viewport.toggleBounds',
    description: '切换包围盒',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleLights',
    keys: [{ key: 'l' }],
    action: 'viewport.toggleLights',
    description: '切换灯光',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleSkybox',
    keys: [{ key: 'k' }],
    action: 'viewport.toggleSkybox',
    description: '切换天空盒',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.toggleFog',
    keys: [{ key: 'f' }],
    action: 'viewport.toggleFog',
    description: '切换雾效',
    category: 'view',
    context: 'viewport',
  },

  // 渲染模式
  {
    id: 'viewport.renderModeSolid',
    keys: [{ key: '1', alt: true }],
    action: 'viewport.setRenderModeSolid',
    description: '实体渲染',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.renderModeWireframe',
    keys: [{ key: '2', alt: true }],
    action: 'viewport.setRenderModeWireframe',
    description: '线框渲染',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.renderModeMaterial',
    keys: [{ key: '3', alt: true }],
    action: 'viewport.setRenderModeMaterial',
    description: '材质预览',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.renderModeLighting',
    keys: [{ key: '4', alt: true }],
    action: 'viewport.setRenderModeLighting',
    description: '光照预览',
    category: 'view',
    context: 'viewport',
  },

  // 对象操作
  {
    id: 'viewport.duplicate',
    keys: [{ key: 'd', ctrl: true }],
    action: 'viewport.duplicate',
    description: '复制选中对象',
    category: 'edit',
    context: 'viewport',
  },
  {
    id: 'viewport.instance',
    keys: [{ key: 'i', ctrl: true }],
    action: 'viewport.instance',
    description: '实例化选中对象',
    category: 'edit',
    context: 'viewport',
  },
  {
    id: 'viewport.delete',
    keys: [{ key: 'Delete' }],
    action: 'viewport.delete',
    description: '删除选中对象',
    category: 'edit',
    context: 'viewport',
  },
  {
    id: 'viewport.hideSelected',
    keys: [{ key: 'h' }],
    action: 'viewport.hideSelected',
    description: '隐藏选中',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.hideUnselected',
    keys: [{ key: 'h', shift: true }],
    action: 'viewport.hideUnselected',
    description: '隐藏未选中',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.showAll',
    keys: [{ key: 'h', ctrl: true }],
    action: 'viewport.showAll',
    description: '显示所有',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.isolateSelected',
    keys: [{ key: 'i' }],
    action: 'viewport.isolateSelected',
    description: '孤立显示',
    category: 'view',
    context: 'viewport',
  },

  // 书签
  {
    id: 'viewport.setBookmark1',
    keys: [{ key: '1', ctrl: true, shift: true }],
    action: 'viewport.setBookmark1',
    description: '设置书签1',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.setBookmark2',
    keys: [{ key: '2', ctrl: true, shift: true }],
    action: 'viewport.setBookmark2',
    description: '设置书签2',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.setBookmark3',
    keys: [{ key: '3', ctrl: true, shift: true }],
    action: 'viewport.setBookmark3',
    description: '设置书签3',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.gotoBookmark1',
    keys: [{ key: '1', shift: true }],
    action: 'viewport.gotoBookmark1',
    description: '跳转书签1',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.gotoBookmark2',
    keys: [{ key: '2', shift: true }],
    action: 'viewport.gotoBookmark2',
    description: '跳转书签2',
    category: 'view',
    context: 'viewport',
  },
  {
    id: 'viewport.gotoBookmark3',
    keys: [{ key: '3', shift: true }],
    action: 'viewport.gotoBookmark3',
    description: '跳转书签3',
    category: 'view',
    context: 'viewport',
  },
];
