//! # Code Generator Trait
//!
//! 代码生成器trait - 将编辑器中的资源转换为Rust代码。
//!
//! ## 核心组件
//!
//! 1. **CodeGenerator** - 代码生成器trait
//! 2. **PrefabGenerator** - 场景Prefab代码生成
//! 3. **ShaderGenerator** - 材质Shader代码生成
//! 4. **ParticleGenerator** - 粒子系统代码生成
//! 5. **BehaviorTreeGenerator** - 行为树代码生成
//!
//! ## 使用示例
//!
//! ```rust,no_run
//! use game_engine::editor::code_generator::*;
//!
//! // 创建Prefab生成器
//! let generator = PrefabGenerator::new(CodeGenOptions::default());
//! let scene = Scene::from_file("scene.json").unwrap();
//! let code = generator.generate(&scene).unwrap();
//! std::fs::write(code.file_path, code.code).unwrap();
//! ```

use std::path::PathBuf;
use thiserror::Error;

/// 代码生成错误
#[derive(Debug, Error)]
pub enum CodeGenError {
    #[error("IO error: {0}")]
    Io(#[from] std::io::Error),

    #[error("Template error: {0}")]
    Template(String),

    #[error("Invalid input: {0}")]
    InvalidInput(String),

    #[error("Generation failed: {0}")]
    GenerationFailed(String),
}

// ==================== 占位类型定义 ====================
// 注意：这些是简化的类型定义，用于框架展示
// 实际实现时应该使用项目中的真实类型

/// 场景占位类型
#[derive(Clone, Debug)]
pub struct Scene {
    pub name: String,
    pub entities: Vec<Entity>,
}

/// 实体占位类型
#[derive(Clone, Debug)]
pub struct Entity {
    pub name: String,
    pub components: Vec<ComponentData>,
}

/// 组件数据占位类型
#[derive(Clone, Debug)]
pub struct ComponentData(String);

/// 材质占位类型
#[derive(Clone, Debug)]
pub struct Material {
    pub name: String,
    pub shader_type: ShaderType,
}

/// 着色器类型
#[derive(Clone, Debug)]
pub enum ShaderType {
    Pbr,
    Unlit,
    Custom,
}

/// 粒子系统占位类型
#[derive(Clone, Debug)]
pub struct ParticleSystem {
    pub name: String,
    pub max_particles: usize,
    pub emission_rate: f32,
    pub lifetime: std::time::Duration,
}

/// 行为树占位类型
#[derive(Clone, Debug)]
pub struct BehaviorTree {
    pub name: String,
    pub root_node: Box<BehaviorNode>,
}

/// 行为节点占位类型
#[derive(Clone, Debug)]
pub struct BehaviorNode;

/// 代码生成结果
#[derive(Clone, Debug)]
pub struct GeneratedCode {
    pub code: String,
    pub file_path: PathBuf,
    pub dependencies: Vec<String>,
}

/// 代码生成器trait
pub trait CodeGenerator<T> {
    /// 生成代码
    fn generate(&self, input: &T) -> Result<GeneratedCode, CodeGenError>;

    /// 验证输入
    fn validate(&self, input: &T) -> Result<(), CodeGenError>;

    /// 获取生成的依赖项
    fn get_dependencies(&self, input: &T) -> Vec<String>;
}

/// 代码生成选项
#[derive(Clone, Debug)]
pub struct CodeGenOptions {
    /// 是否添加文档注释
    pub add_docs: bool,
    /// 是否格式化代码
    pub format_code: bool,
    /// 命名空间前缀
    pub namespace: Option<String>,
    /// 是否生成测试
    pub generate_tests: bool,
}

impl Default for CodeGenOptions {
    fn default() -> Self {
        Self {
            add_docs: true,
            format_code: true,
            namespace: None,
            generate_tests: false,
        }
    }
}

// ==================== 场景Prefab生成器 ====================

/// Prefab生成器
pub struct PrefabGenerator {
    options: CodeGenOptions,
}

impl PrefabGenerator {
    pub fn new(options: CodeGenOptions) -> Self {
        Self { options }
    }

    /// 生成struct定义
    fn generate_struct_def(&self, scene: &Scene) -> String {
        let name = self.sanitize_name(&scene.name);
        let mut code = String::new();

        // 文档注释
        if self.options.add_docs {
            code.push_str(&format!("/// Auto-generated Prefab: {}\n", scene.name));
            code.push_str("///\n");
            code.push_str("/// Generated by game_engine editor\n");
            code.push_str(&format!("/// Entity count: {}\n", scene.entities.len()));
            code.push_str("#[derive(Clone, Debug)]\n");
        }

        // struct定义
        code.push_str(&format!("pub struct {name} {{\n"));

        // 添加字段
        for entity in &scene.entities {
            let field_name = self.sanitize_name(&entity.name);
            let field_type = self.get_entity_type(entity);
            code.push_str(&format!("    pub {field_name}: {field_type},\n"));
        }

        code.push_str("}\n\n");

        // 实现Default
        code.push_str(&format!("impl Default for {name} {{\n"));
        code.push_str("    fn default() -> Self {\n");
        code.push_str("        Self {\n");

        for entity in &scene.entities {
            let field_name = self.sanitize_name(&entity.name);
            code.push_str(&format!(
                "            {}: {}::default(),\n",
                field_name,
                self.get_entity_type(entity)
            ));
        }

        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n\n");

        code
    }

    /// 生成创建函数
    fn generate_creation_func(&self, scene: &Scene) -> String {
        let name = self.sanitize_name(&scene.name);
        let mut code = String::new();

        if self.options.add_docs {
            code.push_str("/// Creates the prefab in the given world\n");
        }

        code.push_str(&format!(
            "pub fn create_{}_prefab(world: &mut World) -> Result<Entity, CreateError> {{\n",
            name.to_lowercase()
        ));

        // 创建根实体
        code.push_str("    let root = world.spawn_empty().id();\n\n");

        // 创建子实体
        for entity in &scene.entities {
            code.push_str(&self.generate_entity_creation(entity, "root"));
        }

        code.push_str("\n    Ok(root)\n");
        code.push_str("}\n\n");

        code
    }

    /// 生成实体创建代码
    fn generate_entity_creation(&self, entity: &Entity, parent: &str) -> String {
        let mut code = String::new();
        let entity_name = self.sanitize_name(&entity.name);

        // 创建实体
        code.push_str(&format!(
            "    let {entity_name} = world.spawn_empty().id();\n"
        ));

        // 添加组件
        for component in &entity.components {
            code.push_str(&format!("    world.entity_mut({entity_name})\n"));
            code.push_str(&format!(
                "        .insert({});\n",
                self.generate_component_init(component)
            ));
        }

        // 设置父子关系
        code.push_str(&format!("    world.entity_mut({entity_name})\n"));
        code.push_str(&format!("        .set_parent_in_place({parent});\n\n"));

        code
    }

    /// 生成组件初始化代码
    fn generate_component_init(&self, component: &ComponentData) -> String {
        // 简化版 - 实际实现需要解析组件数据
        "ComponentData { /* data */ }".to_string()
    }

    /// 获取实体类型
    fn get_entity_type(&self, _entity: &Entity) -> String {
        "Entity".to_string()
    }

    /// 清理名称为合法Rust标识符
    fn sanitize_name(&self, name: &str) -> String {
        name.chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>()
            .trim_matches('_')
            .to_string()
    }
}

impl CodeGenerator<Scene> for PrefabGenerator {
    fn generate(&self, scene: &Scene) -> Result<GeneratedCode, CodeGenError> {
        self.validate(scene)?;

        let mut code = String::new();

        // 文件头
        code.push_str("// Auto-generated by game_engine editor\n");
        code.push_str("// DO NOT EDIT MANUALLY\n\n");
        code.push_str("use bevy_ecs::world::World;\n");
        code.push_str("use bevy_ecs::entity::Entity;\n\n");

        // 生成struct定义
        code.push_str(&self.generate_struct_def(scene));

        // 生成创建函数
        code.push_str(&self.generate_creation_func(scene));

        // 生成测试（可选）
        if self.options.generate_tests {
            // TODO: 实现测试生成
            code.push_str("\n// Tests will be generated here\n");
        }

        let file_name = format!(
            "{}_prefab.rs",
            self.sanitize_name(&scene.name).to_lowercase()
        );

        Ok(GeneratedCode {
            code,
            file_path: PathBuf::from(file_name),
            dependencies: vec!["bevy_ecs".to_string()],
        })
    }

    fn validate(&self, scene: &Scene) -> Result<(), CodeGenError> {
        if scene.name.is_empty() {
            return Err(CodeGenError::InvalidInput(
                "Scene name is empty".to_string(),
            ));
        }
        if scene.entities.is_empty() {
            return Err(CodeGenError::InvalidInput(
                "Scene has no entities".to_string(),
            ));
        }
        Ok(())
    }

    fn get_dependencies(&self, _scene: &Scene) -> Vec<String> {
        vec!["bevy_ecs".to_string()]
    }
}

// ==================== 材质Shader生成器 ====================

/// Shader生成器
pub struct ShaderGenerator {
    options: CodeGenOptions,
}

impl ShaderGenerator {
    pub fn new(options: CodeGenOptions) -> Self {
        Self { options }
    }

    /// 生成顶点着色器
    fn generate_vertex_shader(&self, material: &Material) -> String {
        let mut code = String::new();

        if self.options.add_docs {
            code.push_str("// Vertex shader for material\n");
            code.push_str(&format!("// Material: {}\n", material.name));
        }

        code.push_str("\nstruct VertexInput {\n");
        code.push_str("    @location(0) position: vec3<f32>,\n");
        code.push_str("    @location(1) normal: vec3<f32>,\n");
        code.push_str("    @location(2) uv: vec2<f32>,\n");
        code.push_str("}\n\n");

        code.push_str("struct VertexOutput {\n");
        code.push_str("    @builtin(position) clip_position: vec4<f32>,\n");
        code.push_str("    @location(0) uv: vec2<f32>,\n");
        code.push_str("    @location(1) normal: vec3<f32>,\n");
        code.push_str("}\n\n");

        code.push_str("@vertex\n");
        code.push_str("fn vs_main(input: VertexInput) -> VertexOutput {\n");
        code.push_str("    var output: VertexOutput;\n");
        code.push_str("    output.clip_position = vec4<f32>(input.position, 1.0);\n");
        code.push_str("    output.uv = input.uv;\n");
        code.push_str("    output.normal = input.normal;\n");
        code.push_str("    return output;\n");
        code.push_str("}\n");

        code
    }

    /// 生成片段着色器
    fn generate_fragment_shader(&self, material: &Material) -> String {
        let mut code = String::new();

        if self.options.add_docs {
            code.push_str("// Fragment shader for material\n");
            code.push_str(&format!("// Material: {}\n", material.name));
        }

        code.push_str("\n@group(0) @binding(0)\n");
        code.push_str("var texture_sampler: sampler;\n\n");

        code.push_str("@group(0) @binding(1)\n");
        code.push_str("var base_color_texture: texture_2d<f32>;\n\n");

        code.push_str("struct FragmentInput {\n");
        code.push_str("    @location(0) uv: vec2<f32>,\n");
        code.push_str("    @location(1) normal: vec3<f32>,\n");
        code.push_str("}\n\n");

        code.push_str("struct FragmentOutput {\n");
        code.push_str("    @location(0) color: vec4<f32>,\n");
        code.push_str("}\n\n");

        code.push_str("@fragment\n");
        code.push_str("fn fs_main(input: FragmentInput) -> FragmentOutput {\n");
        code.push_str("    var output: FragmentOutput;\n");
        code.push_str(
            "    let color = textureSample(base_color_texture, texture_sampler, input.uv);\n",
        );
        code.push_str("    output.color = color;\n");
        code.push_str("    return output;\n");
        code.push_str("}\n");

        code
    }
}

impl CodeGenerator<Material> for ShaderGenerator {
    fn generate(&self, material: &Material) -> Result<GeneratedCode, CodeGenError> {
        self.validate(material)?;

        let vs_code = self.generate_vertex_shader(material);
        let fs_code = self.generate_fragment_shader(material);

        let full_code = format!("// Vertex Shader\n{vs_code}\n\n// Fragment Shader\n{fs_code}");

        let file_name = format!(
            "{}_shader.wgsl",
            self.sanitize_name(&material.name).to_lowercase()
        );

        Ok(GeneratedCode {
            code: full_code,
            file_path: PathBuf::from(file_name),
            dependencies: vec![],
        })
    }

    fn validate(&self, material: &Material) -> Result<(), CodeGenError> {
        if material.name.is_empty() {
            return Err(CodeGenError::InvalidInput(
                "Material name is empty".to_string(),
            ));
        }
        Ok(())
    }

    fn get_dependencies(&self, _material: &Material) -> Vec<String> {
        vec![]
    }
}

impl ShaderGenerator {
    fn sanitize_name(&self, name: &str) -> String {
        name.chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>()
            .trim_matches('_')
            .to_string()
    }
}

// ==================== 粒子系统生成器 ====================

/// 粒子系统代码生成器
pub struct ParticleGenerator {
    options: CodeGenOptions,
}

impl ParticleGenerator {
    pub fn new(options: CodeGenOptions) -> Self {
        Self { options }
    }

    /// 生成粒子系统配置代码
    fn generate_config(&self, system: &ParticleSystem) -> String {
        let name = self.sanitize_name(&system.name);
        let mut code = String::new();

        if self.options.add_docs {
            code.push_str(&format!("/// Particle System: {}\n", system.name));
            code.push_str(&format!("/// Max particles: {}\n", system.max_particles));
        }

        code.push_str(&format!("pub struct {name}Config {{\n"));
        code.push_str(&format!(
            "    pub max_particles: usize, // {}\n",
            system.max_particles
        ));
        code.push_str(&format!(
            "    pub emission_rate: f32, // {} per second\n",
            system.emission_rate
        ));
        code.push_str(&format!(
            "    pub lifetime: std::time::Duration, // {:?}\n",
            system.lifetime
        ));
        code.push_str("    pub color: Color,\n");
        code.push_str("    pub size: Vec2,\n");
        code.push_str("}\n\n");

        // 实现Default
        code.push_str(&format!("impl Default for {name}Config {{\n"));
        code.push_str("    fn default() -> Self {\n");
        code.push_str("        Self {\n");
        code.push_str(&format!(
            "            max_particles: {},\n",
            system.max_particles
        ));
        code.push_str(&format!(
            "            emission_rate: {},\n",
            system.emission_rate
        ));
        code.push_str(&format!(
            "            lifetime: std::time::Duration::from_secs_f32({}),\n",
            system.lifetime.as_secs_f32()
        ));
        code.push_str("            color: Color::WHITE,\n");
        code.push_str("            size: Vec2::splat(1.0),\n");
        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n");

        code
    }
}

impl CodeGenerator<ParticleSystem> for ParticleGenerator {
    fn generate(&self, system: &ParticleSystem) -> Result<GeneratedCode, CodeGenError> {
        self.validate(system)?;

        let mut code = String::new();

        code.push_str("// Auto-generated particle system configuration\n\n");
        code.push_str("use bevy_math::Vec2;\n");
        code.push_str("use game_engine::render::Color;\n\n");

        code.push_str(&self.generate_config(system));

        let file_name = format!(
            "{}_particles.rs",
            self.sanitize_name(&system.name).to_lowercase()
        );

        Ok(GeneratedCode {
            code,
            file_path: PathBuf::from(file_name),
            dependencies: vec!["bevy_math".to_string()],
        })
    }

    fn validate(&self, system: &ParticleSystem) -> Result<(), CodeGenError> {
        if system.name.is_empty() {
            return Err(CodeGenError::InvalidInput(
                "ParticleSystem name is empty".to_string(),
            ));
        }
        if system.max_particles == 0 {
            return Err(CodeGenError::InvalidInput(
                "Max particles is zero".to_string(),
            ));
        }
        Ok(())
    }

    fn get_dependencies(&self, _system: &ParticleSystem) -> Vec<String> {
        vec!["bevy_math".to_string()]
    }
}

impl ParticleGenerator {
    fn sanitize_name(&self, name: &str) -> String {
        name.chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>()
            .trim_matches('_')
            .to_string()
    }
}

// ==================== 行为树生成器 ====================

/// 行为树代码生成器
pub struct BehaviorTreeGenerator {
    options: CodeGenOptions,
}

impl BehaviorTreeGenerator {
    pub fn new(options: CodeGenOptions) -> Self {
        Self { options }
    }

    /// 生成行为树定义
    fn generate_tree_def(&self, tree: &BehaviorTree) -> String {
        let name = self.sanitize_name(&tree.name);
        let mut code = String::new();

        if self.options.add_docs {
            code.push_str(&format!("/// Behavior Tree: {}\n", tree.name));
            code.push_str("/// Auto-generated from editor\n");
        }

        code.push_str(&format!("pub struct {name}BehaviorTree {{\n"));
        code.push_str("    pub root: Box<dyn BehaviorNode>,\n");
        code.push_str("}\n\n");

        // 实现Builder模式
        code.push_str(&format!("impl {name}BehaviorTree {{\n"));
        code.push_str("    pub fn new() -> Self {\n");
        code.push_str("        Self {\n");
        code.push_str("            root: Box::new(SelectorNode::new()),\n");
        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n");

        code
    }
}

impl CodeGenerator<BehaviorTree> for BehaviorTreeGenerator {
    fn generate(&self, tree: &BehaviorTree) -> Result<GeneratedCode, CodeGenError> {
        self.validate(tree)?;

        let mut code = String::new();

        code.push_str("// Auto-generated behavior tree\n\n");
        code.push_str("use game_engine::ai::behavior_tree::*;\n\n");

        code.push_str(&self.generate_tree_def(tree));

        let file_name = format!(
            "{}_behavior.rs",
            self.sanitize_name(&tree.name).to_lowercase()
        );

        Ok(GeneratedCode {
            code,
            file_path: PathBuf::from(file_name),
            dependencies: vec!["game_engine::ai".to_string()],
        })
    }

    fn validate(&self, tree: &BehaviorTree) -> Result<(), CodeGenError> {
        if tree.name.is_empty() {
            return Err(CodeGenError::InvalidInput(
                "BehaviorTree name is empty".to_string(),
            ));
        }
        Ok(())
    }

    fn get_dependencies(&self, _tree: &BehaviorTree) -> Vec<String> {
        vec!["game_engine::ai".to_string()]
    }
}

impl BehaviorTreeGenerator {
    fn sanitize_name(&self, name: &str) -> String {
        name.chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>()
            .trim_matches('_')
            .to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_codegen_options_default() {
        let options = CodeGenOptions::default();
        assert!(options.add_docs);
        assert!(options.format_code);
        assert!(options.namespace.is_none());
        assert!(!options.generate_tests);
    }

    #[test]
    fn test_sanitize_name() {
        let generator = PrefabGenerator::new(CodeGenOptions::default());
        assert_eq!(generator.sanitize_name("Test Scene"), "Test_Scene");
        assert_eq!(generator.sanitize_name("test-scene"), "testscene");
    }
}
