//! 2D Brick Breaker Game - C# Scripting Example
//!
//! A classic brick breaker game implemented using C# scripts.
//!
//! Features:
//! - C# script components for all game logic
//! - Physics-based collision detection
//! - Score and lives system
//! - Particle effects
//! - Audio feedback
//!
//! Run:
//! ```bash
//! cargo run --example brick_breaker --features csharp
//! ```

#[cfg(feature = "csharp")]
use game_engine::{
    core::EngineBuilder,
    scripting::{CSharpHost, ScriptType},
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Initialize logger
    tracing_subscriber::fmt()
        .with_env_filter("game_engine=debug,csharp=trace,brick_breaker=info")
        .init();

    println!("🎮 2D Brick Breaker - C# Scripting Example");
    println!("{}", "=".repeat(50));

    // Build the engine
    let mut engine = EngineBuilder::new()
        .with_window_title("Brick Breaker - C# Scripts")
        .with_window_size(800, 600)
        .with_scripts_enabled(true)
        .build()?;

    // Initialize C# host
    let csharp_host = CSharpHost::new()?
        .with_script_type(ScriptType::File)
        .with_auto_reload(true)
        .initialize()?;

    println!("✅ C# runtime initialized");
    println!("✅ Engine ready");

    // Load C# scripts
    load_scripts(&csharp_host)?;

    // Create game entities
    create_game_entities(&mut engine)?;

    // Run the game loop
    println!("🎯 Starting game...");
    engine.run();

    Ok(())
}

/// Load all C# scripts
#[cfg(feature = "csharp")]
fn load_scripts(host: &CSharpHost) -> Result<(), Box<dyn std::error::Error>> {
    println!("\n📜 Loading C# scripts...");

    // Load component scripts
    let component_scripts = [
        "scripts/Components/Ball.cs",
        "scripts/Components/Paddle.cs",
        "scripts/Components/Brick.cs",
        "scripts/Components/GameManager.cs",
    ];

    for script in &component_scripts {
        match host.load_script(script) {
            Ok(_) => println!("  ✅ Loaded: {}", script),
            Err(e) => eprintln!("  ❌ Failed to load {}: {}", script, e),
        }
    }

    // Load system scripts
    let system_scripts = [
        "scripts/Systems/PhysicsSystem.cs",
        "scripts/Systems/CollisionSystem.cs",
        "scripts/Systems/ScoreSystem.cs",
    ];

    for script in &system_scripts {
        match host.load_script(script) {
            Ok(_) => println!("  ✅ Loaded: {}", script),
            Err(e) => eprintln!("  ❌ Failed to load {}: {}", script, e),
        }
    }

    // Load game logic
    match host.load_script("scripts/Game/GameLogic.cs") {
        Ok(_) => println!("  ✅ Loaded: scripts/Game/GameLogic.cs"),
        Err(e) => eprintln!("  ❌ Failed to load GameLogic.cs: {}", e),
    }

    Ok(())
}

/// Create game entities
#[cfg(feature = "csharp")]
fn create_game_entities(engine: &mut game_engine::core::Engine) -> Result<(), Box<dyn std::error::Error>> {
    println!("\n🎨 Creating game entities...");

    let world = &mut engine.world;

    // Create paddle
    let paddle = world.create_entity();
    paddle.set_name("Paddle");
    paddle.add_component(game_engine::ecs::Transform::default());
    // Note: C# components are attached at runtime

    println!("  ✅ Created paddle entity");

    // Create ball
    let ball = world.create_entity();
    ball.set_name("Ball");
    ball.add_component(game_engine::ecs::Transform::default());

    println!("  ✅ Created ball entity");

    // Create game manager
    let manager = world.create_entity();
    manager.set_name("GameManager");

    println!("  ✅ Created game manager entity");

    // Create bricks (will be generated by GameManager at runtime)

    Ok(())
}

// Stub implementation when csharp feature is not enabled
#[cfg(not(feature = "csharp"))]
fn main() {
    println!("⚠️  This example requires the 'csharp' feature");
    println!("\nTo run this example:");
    println!("  cargo run --example brick_breaker --features csharp");
    println!("\nInstall .NET SDK 8.0:");
    println!("  macOS:   brew install --cask dotnet-sdk");
    println!("  Linux:   https://dotnet.microsoft.com/download");
    println!("  Windows: https://dotnet.microsoft.com/download");
}
