pub mod batch_renderer;
pub mod object_pool;
pub mod profiler;
pub mod render_optimization;
pub mod advanced_profiler;
pub mod continuous_profiler;
pub mod memory_profiler;
pub mod synchronized;
pub mod arena;
pub mod simd;
pub mod hardware;

pub use batch_renderer::BatchRenderer;
pub use object_pool::{ObjectPool, SyncObjectPool, ResettablePool, Pooled, PoolStats, Resettable, SizedPool};
pub use profiler::Profiler;
pub use render_optimization::{FrustumCulling, OcclusionCulling, LodManager};
pub use advanced_profiler::{AdvancedProfiler, PerformanceMetrics};
pub use continuous_profiler::ContinuousProfiler;
pub use memory_profiler::{MemoryProfiler, GpuProfiler};
pub use simd::{CpuFeatures, detect_cpu_features, print_cpu_info};
pub use hardware::{get_hardware_info, print_hardware_info, HardwareInfo, AutoConfig};
pub use arena::{Arena, TypedArena, TypedArenaWithDrop, ArenaError, MemoryPool};
