//! AI代码生成器

use super::{AIConfig, AIError, AIProvider};
use serde::{Deserialize, Serialize};

/// AI代码生成器
pub struct AICodeGenerator {
    config: AIConfig,
}

impl AICodeGenerator {
    /// 创建新生成器
    pub fn new(config: AIConfig) -> Self {
        Self { config }
    }

    /// 生成代码
    pub async fn generate(&self, request: CodeGenerationRequest) -> Result<String, AIError> {
        // TODO: 实现实际的API调用
        // 这里使用框架实现

        let prompt = self.build_prompt(&request);

        match self.config.provider {
            AIProvider::OpenAI => {
                self.call_openai(&prompt).await
            }
            AIProvider::Anthropic => {
                self.call_anthropic(&prompt).await
            }
            AIProvider::Local => {
                self.call_local(&prompt).await
            }
            AIProvider::Other => {
                Err(AIError::Other("Unsupported provider".to_string()))
            }
        }
    }

    /// 构建提示词
    fn build_prompt(&self, request: &CodeGenerationRequest) -> String {
        format!(
            "Generate {} code for the following:\n\nDescription: {}\n\nContext:\n{}",
            request.language, request.description, request.context
        )
    }

    /// 调用OpenAI API
    async fn call_openai(&self, prompt: &str) -> Result<String, AIError> {
        // TODO: 实际API调用
        // 模拟响应
        Ok(format!("// Generated by OpenAI\n// Prompt: {}", prompt))
    }

    /// 调用Anthropic API
    async fn call_anthropic(&self, prompt: &str) -> Result<String, AIError> {
        // TODO: 实际API调用
        // 模拟响应
        Ok(format!("// Generated by Anthropic\n// Prompt: {}", prompt))
    }

    /// 调用本地模型
    async fn call_local(&self, prompt: &str) -> Result<String, AIError> {
        // TODO: 实际本地模型调用
        // 模拟响应
        Ok(format!("// Generated by Local Model\n// Prompt: {}", prompt))
    }
}

/// 代码生成请求
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeGenerationRequest {
    /// 编程语言
    pub language: String,
    /// 描述
    pub description: String,
    /// 上下文
    pub context: String,
    /// 代码风格
    pub style: Option<String>,
}

impl CodeGenerationRequest {
    /// 创建新请求
    pub fn new(language: String, description: String, context: String) -> Self {
        Self {
            language,
            description,
            context,
            style: None,
        }
    }

    /// 设置代码风格
    pub fn with_style(mut self, style: String) -> Self {
        self.style = Some(style);
        self
    }
}

// =============================================================================
// 测试
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_code_generation() {
        let config = AIConfig::default();
        let generator = AICodeGenerator::new(config);

        let request = CodeGenerationRequest::new(
            "Rust".to_string(),
            "A function to add two numbers".to_string(),
            "Game engine math module".to_string(),
        );

        let result = generator.generate(request).await;
        assert!(result.is_ok());
    }
}
